Test 'Where does my donation go' link
wmde/Dandy pull request #2
Opened 2022-11-17 15:56 UTC by Sperling-0

2022-11-18 05:55 UTC, Abban requested changes
I forgot to add to the new documentation that each test should check for something as that's what these tests are for: `Perform actions -> Check result is as expected`. I've mentioned what you can do to add that in the review comments.

The screenshots aren't used for the tests other than letting you see what the page looks like if a test fails. They're more of a developer tool, you'll see the real feedback in your terminal when you run the tests.

This is a good start, though!

2022-11-18 05:55 UTC, Abban commented on config/banners.js
> +		where_does_my_donation_go_link: {
It'd probably be better to call this `use_of_funds` (as that's what we call the content in the modal) and the sub item isn't a form but a link. Also you can add a selector to check if the modal is open:

```suggestion
		use_of_funds: {
		    link: '.wmde-banner-footer-usage-link',
		    modal_is_open: '.banner_modal.is-visible'
```

2022-11-18 05:55 UTC, Abban commented on pages/Banner.js
> +		this.dandy.click( bannerConfig.selectors.where_does_my_donation_go_link.form );
```suggestion
		this.dandy.click( bannerConfig.selectors.use_of_funds.link );
```

2022-11-18 05:55 UTC, Abban commented on pages/Banner.js
> +	clickWhereDoesMyDonationGoLink() {
```suggestion
	clickUseOfFundsLink() {
```

2022-11-18 05:55 UTC, Abban commented on tests/banners/where-does-my-donation-go.js
> +import { bannerConfig } from '../../config/banners.js';
This file should be called something more descriptive of the action, maybe `desktop-shows-use-of-funds.js`

2022-11-18 05:55 UTC, Abban commented on pages/Banner.js
> +
You need to add a method that checks that the Use of Funds is visible:

```js
checkUseOfFundsIsVisible() {
	this.dandy.checkElementExists( bannerConfig.selectors.use_of_funds.modal_is_open );
	return this;
}
```

2022-11-18 05:55 UTC, Abban commented on tests/banners/where-does-my-donation-go.js
> +		.clickWhereDoesMyDonationGoLink()
```suggestion
		.clickUseOfFundsLink()
		.checkUseOfFundsIsVisible()
```

2022-11-23 11:25 UTC, gbirke approved these changes

2022-11-25 12:34 UTC, Abban commented on pages/Banner.js
> +		this.dandy.checkElementExists( bannerConfig.selectors.use_of_funds.modal_is_open );
All you need to check here is if the modal is open as that's what this test is for. You can leave the selectors in the config though, as we might write a test that needs to select them in the future.

2023-02-17 11:12 UTC, Abban commented
This was done in https://github.com/wmde/Dandy/pull/8

2023-02-17 11:12 UTC, closed without merging